name: Build APK Agent-maung
on:
  workflow_dispatch:

jobs:
  bikin_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari Agent-maung
        uses: actions/checkout@v4

      - name: Pasang semua alat
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libffi-dev libssl-dev build-essential
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Proses bikin APK
        run: |
          export CFLAGS="-I/usr/include"
          export LDFLAGS="-L/usr/lib"
          buildozer android debug

      - name: Simpan hasilnya
        uses: actions/upload-artifact@v4
        with:
          name: AGENT_MAUNG_APK
          path: bin/agentmaung-debug.apk
