name: Build APK Agent-maung
on:
  workflow_dispatch:

jobs:
  bikin_apk:
    runs-on: ubuntu-22.04
    env:
      # PENTING: Paksa simpan di folder kerja kita, biar izin aman
      ANDROID_SDK: ${{ github.workspace }}/sdk
      ANDROID_NDK: ${{ github.workspace }}/ndk
    steps:
      - name: Ambil kode
        uses: actions/checkout@v4

      - name: Pasang alat dasar
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-11-jdk python3-pip build-essential libssl-dev zlib1g-dev libffi-dev
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Bikin folder tempat simpan SDK (aman & izin penuh)
        run: |
          mkdir -p $ANDROID_SDK
          mkdir -p $ANDROID_NDK
          echo "ANDROID_SDK=$ANDROID_SDK" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV

      - name: Mulai bikin APK
        run: |
          buildozer android debug --verbose

      - name: Simpan hasil
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AGENT_MAUNG_BERHASIL
          path: bin/*.apk
